(function() {var implementors = {};
implementors["sgx_trts"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"sgx_trts/c_str/struct.CString.html\" title=\"struct sgx_trts::c_str::CString\">CString</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;u8&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"struct\" href=\"sgx_trts/c_str/struct.CStr.html\" title=\"struct sgx_trts::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;<a class=\"struct\" href=\"sgx_trts/c_str/struct.CStr.html\" title=\"struct sgx_trts::c_str::CStr\">CStr</a>&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;<a class=\"struct\" href=\"sgx_trts/c_str/struct.CStr.html\" title=\"struct sgx_trts::c_str::CStr\">CStr</a>&gt;&gt; for <a class=\"struct\" href=\"sgx_trts/c_str/struct.CString.html\" title=\"struct sgx_trts::c_str::CString\">CString</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"sgx_trts/c_str/struct.CString.html\" title=\"struct sgx_trts::c_str::CString\">CString</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;<a class=\"struct\" href=\"sgx_trts/c_str/struct.CStr.html\" title=\"struct sgx_trts::c_str::CStr\">CStr</a>&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"struct\" href=\"sgx_trts/c_str/struct.CStr.html\" title=\"struct sgx_trts::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"sgx_trts/c_str/struct.CString.html\" title=\"struct sgx_trts::c_str::CString\">CString</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
